platform :ios, '15.0'

use_frameworks!
inhibit_all_warnings!

project 'SwiftApp'
workspace 'SwiftApp'

source 'https://bancopan.visualstudio.com/commons-lib/_git/mobile-ios--pan-podspecs'
source 'https://github.com/CocoaPods/Specs.git'

def shared_pods  
  pod 'SwiftRouterService', path: '../'
end

target 'SwiftApp' do
  shared_pods
end

target 'SwiftAppTests' do
  shared_pods
end

post_install do |installer|  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_INSTALL_OBJC_HEADER'] = 'No'
    end
  end
  
end
