name: CI iOS Nativo

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. Baixa o código do seu repositório
      - name: Checkout do repositório
        uses: actions/checkout@v4

      # 2. Configura a versão do Xcode (Garante compatibilidade com o seu código)
      - name: Selecionar versão do Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      # 3. Instala e executa o XcodeGen para criar o arquivo .xcodeproj
      - name: Instalar e rodar XcodeGen
        run: |
          brew install xcodegen
          xcodegen generate --spec Example/project.yml

      # 4. Instala as dependências do CocoaPods
      # Nota: O CocoaPods já vem pré-instalado nos ambientes macOS do GitHub Actions
      - name: Instalar dependências (CocoaPods)
        working-directory: Example
        run: |
          pod install

      # 5. Executa a compilação voltada para o Simulador (não exige assinatura de perfil)
      - name: Compilar aplicativo para Simulador iOS
        run: |
          xcodebuild build \
            -scheme SwiftApp \
            -workspace ./Example/SwiftApp.xcworkspace \
            -destination 'generic/platform=iOS Simulator' \
            -configuration Debug
